version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aiworkflow_backend  # 显式
    ports:
      - "3001:3001"
    env_file:
      - .env  # Docker 会自动读取 .env 并将其中的变量注入系统环境
    networks:
      - aiworkflow-network

networks:
  aiworkflow-network:
    driver: bridge